# docker-compose.yml

version: "3.0"
services:
  frontapp:
    build: ./FrontEnd/app
    image: taekyungss/frontapp:latest  # 태그를 명시적으로 지정
    ports:
      - "80:80"

  backapp:
    build: ./BackEnd
    image: taekyungss/backapp:latest  # 태그를 명시적으로 지정
    ports:
      - "8080:8080"
